[package]
name = "cloudemu-ui"
version.workspace = true
edition = "2024"

[dependencies]
dioxus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
