[package]
name = "azure-control-facade"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "azure control facade"

[dependencies]
azure-control-spi = { path = "../azure-control-spi" }
azure-control-core = { path = "../azure-control-core" }
azure-control-api = { path = "../azure-control-api" }

axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
http-body-util = "0.1"
clap = { version = "4.0", features = ["derive", "env"] }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }


[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }

