[package]
name = "azure-data-api"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "azure data api"

[dependencies]
azure-data-spi = { path = "../azure-data-spi" }
async-trait = "0.1"

